Basic Structure of service to filter by email
vinsol-spree-contrib/spree_customer_segmentation pull request #2
Opened 2018-06-20 09:57 UTC by shivamvinsol

2018-06-20 10:25 UTC, sawangupta92 requested changes

2018-06-20 10:25 UTC, sawangupta92 commented on app/services/spree/customer_segmentation/base_service.rb
> +      @collection = collection
att_accessor

2018-06-20 10:25 UTC, sawangupta92 commented on app/services/spree/customer_segmentation/search_service.rb
> +      @collection = User.all
attr_accessor

2018-06-20 10:25 UTC, sawangupta92 commented on app/services/spree/customer_segmentation/search_service.rb
> +        @result = CUSTOMER_SEGMENTATION_SERVICE_MAPPER[service_name_key].new(@collection, operator, option[:value]).filter_data
rename CUSTOMER_SEGMENTATION_SERVICE_MAPPER

2018-06-24 18:28 UTC, sawangupta92 requested changes

2018-06-24 18:28 UTC, sawangupta92 commented on app/controllers/spree/admin/customer_segmentation_controller.rb
> +      def apply_sorting
why do we need this?

2018-06-24 18:28 UTC, sawangupta92 commented on app/models/spree/user_decorator.rb
> +  def name
let's delegate them to address.

2018-06-24 18:28 UTC, sawangupta92 commented on app/controllers/spree/admin/customer_segmentation_controller.rb
> +      def create_term
let's use two different params instead metric and operator separately

2018-06-27 11:11 UTC, shivamvinsol commented
closing, work included in #3

2018-06-27 11:12 UTC, closed without merging